#!/bin/bash

FILES=`find . | grep md$`

OP=`cat README_main.md`

echo $FILES

for FILE in $FILES 
do
	if [ ! $FILE == "./README.md" ]
	then
		if [ ! $FILE == "./README_main.md" ]
		then
			OP+=`cat $FILE`
			OP+=$"\n\n"
		fi	
	fi
done

printf "%s", "$OP" > README.md